# Generated by Django 3.0 on 2022-06-26 11:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=30)),
                ('bus_no', models.CharField(max_length=15)),
                ('bus_img', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=15)),
                ('complaint', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Owner_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bus_Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_st', models.CharField(max_length=50)),
                ('stops', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('last_st', models.CharField(max_length=50)),
                ('first_ti', models.CharField(max_length=50)),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('last_ti', models.CharField(max_length=50)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Bus')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Owner_reg'),
        ),
    ]
