# Generated by Django 3.0 on 2022-06-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='bcd',
            field=models.CharField(default='jj', max_length=50),
            preserve_default=False,
        ),
    ]
