# Generated by Django 3.0 on 2022-06-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_test_bcd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
