# Generated by Django 3.0 on 2022-06-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus_Route',
        ),
    ]
