# Generated by Django 3.0 on 2022-06-26 11:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_delete_bus_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_st', models.CharField(max_length=50)),
                ('stops', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('last_st', models.CharField(max_length=50)),
                ('first_ti', models.CharField(max_length=50)),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('last_ti', models.CharField(max_length=50)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Bus')),
            ],
        ),
    ]
